import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'dart:ui';
import '../../../core/colors.dart';
import '../../../core/typography.dart';
import '../../../models/multiplayer.dart';
import '../../../providers/multiplayer_provider.dart';
import '../../../providers/app_providers.dart';
import '../../../core/page_route.dart';
import 'multiplayer_lobby_screen.dart';

class HostSetupScreen extends ConsumerStatefulWidget {
  const HostSetupScreen({super.key});

  @override
  ConsumerState<HostSetupScreen> createState() => _HostSetupScreenState();
}

class _HostSetupScreenState extends ConsumerState<HostSetupScreen>
    with SingleTickerProviderStateMixin {
  String _selectedTheme = 'Daily Life';
  LiveGameType _gameType = LiveGameType.vocabulary;
  int _questionCount = 10;
  int _timeLimit = 15;
  int _maxPlayers = 5;
  bool _playAsParticipant = true;
  final TextEditingController _titleController = TextEditingController(
    text: 'My Forest Quiz',
  );

  late AnimationController _pulseController;
  late Animation<double> _pulseAnimation;

  final List<String> _themes = [
    'Daily Life',
    'Universal Verbs',
    'Time & Space',
    'Grammar Functions',
    'Society & Culture',
  ];

  @override
  void initState() {
    super.initState();
    _pulseController = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 2),
    )..repeat(reverse: true);
    _pulseAnimation = Tween<double>(begin: 1.0, end: 1.05).animate(
      CurvedAnimation(parent: _pulseController, curve: Curves.easeInOut),
    );
  }

  @override
  void dispose() {
    _pulseController.dispose();
    _titleController.dispose();
    super.dispose();
  }

  Future<void> _createGame() async {
    // Show premium creation loading
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => BackdropFilter(
        filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
        child: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const CircularProgressIndicator(color: SeedlingColors.autumnGold),
              const SizedBox(height: 20),
              Text(
                'Planting your Arena...',
                style: SeedlingTypography.body.copyWith(
                  color: Colors.white,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
        ),
      ),
    );

    try {
      final session = LiveGameSession(
        id: '', // Generated by DB
        hostId: '', // Set by provider
        hostName: '',
        title: _titleController.text,
        gameType: _gameType,
        theme: _selectedTheme,
        subtheme: 'General',
        totalQuestions: _questionCount,
        timePerQuestion: _timeLimit,
        maxPlayers: _maxPlayers,
        languageCode: ref.read(nativeLanguageProvider),
        targetLanguageCode: ref.read(currentLanguageProvider),
      );

      await ref.read(activeSessionProvider.notifier).hostGame(session);

      if (mounted) {
        Navigator.pop(context); // Close loading
        Navigator.pushReplacement(
          context,
          SeedlingPageRoute(
            page: MultiplayerLobbyScreen(
              session: ref.read(activeSessionProvider)!,
            ),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        Navigator.pop(context); // Close loading
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            backgroundColor: SeedlingColors.hibiscusRed,
            content: Text(
              'Failed to create arena: $e',
              style: const TextStyle(color: Colors.white),
            ),
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0A1208), // Deep forest ground
      body: Stack(
        children: [
          _buildMeshGradient(),

          SafeArea(
            child: CustomScrollView(
              physics: const BouncingScrollPhysics(),
              slivers: [
                _buildSliverAppBar(),
                SliverPadding(
                  padding: const EdgeInsets.fromLTRB(24, 10, 24, 40),
                  sliver: SliverList(
                    delegate: SliverChildListDelegate([
                      _buildSectionHeader('Arena Identity'),
                      const SizedBox(height: 16),
                      _buildGlassInput(),

                      const SizedBox(height: 32),
                      _buildSectionHeader('Battle Mode'),
                      const SizedBox(height: 16),
                      _buildModeSelection(),

                      const SizedBox(height: 32),
                      _buildSectionHeader('Select Theme'),
                      const SizedBox(height: 16),
                      _buildThemeSelector(),

                      const SizedBox(height: 32),
                      _buildSectionHeader('Game Parameters'),
                      const SizedBox(height: 16),
                      _buildParameterControls(),

                      const SizedBox(height: 32),
                      _buildSectionHeader('Host Preferences'),
                      const SizedBox(height: 16),
                      _buildHostToggle(),

                      const SizedBox(height: 48),
                      _buildCreateButton(),
                      const SizedBox(height: 40),
                    ]),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildMeshGradient() {
    return Stack(
      children: [
        Positioned(
          top: -100,
          right: -50,
          child: Container(
            width: 400,
            height: 400,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              gradient: RadialGradient(
                colors: [
                  SeedlingColors.seedlingGreen.withValues(alpha: 0.15),
                  Colors.transparent,
                ],
              ),
            ),
          ),
        ),
        Positioned(
          top: 200,
          left: -100,
          child: Container(
            width: 350,
            height: 350,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              gradient: RadialGradient(
                colors: [
                  SeedlingColors.autumnGold.withValues(alpha: 0.1),
                  Colors.transparent,
                ],
              ),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildSliverAppBar() {
    return SliverAppBar(
      backgroundColor: Colors.transparent,
      elevation: 0,
      expandedHeight: 120,
      floating: false,
      pinned: true,
      leading: IconButton(
        icon: Container(
          padding: const EdgeInsets.all(8),
          decoration: BoxDecoration(
            color: Colors.white.withValues(alpha: 0.1),
            shape: BoxShape.circle,
          ),
          child: const Icon(
            Icons.arrow_back_ios_new_rounded,
            color: Colors.white,
            size: 18,
          ),
        ),
        onPressed: () => Navigator.pop(context),
      ),
      flexibleSpace: FlexibleSpaceBar(
        titlePadding: const EdgeInsets.only(left: 64, bottom: 16),
        title: Text(
          'Forge New Arena',
          style: SeedlingTypography.heading2.copyWith(color: Colors.white),
        ),
        background: ClipRect(
          child: BackdropFilter(
            filter: ImageFilter.blur(sigmaX: 5, sigmaY: 5),
            child: Container(color: Colors.transparent),
          ),
        ),
      ),
    );
  }

  Widget _buildSectionHeader(String title) {
    return Row(
      children: [
        Container(
          width: 4,
          height: 18,
          decoration: BoxDecoration(
            color: SeedlingColors.autumnGold,
            borderRadius: BorderRadius.circular(2),
          ),
        ),
        const SizedBox(width: 12),
        Text(
          title.toUpperCase(),
          style: SeedlingTypography.caption.copyWith(
            color: Colors.white70,
            letterSpacing: 1.5,
            fontWeight: FontWeight.bold,
          ),
        ),
      ],
    );
  }

  Widget _buildGlassInput() {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white.withValues(alpha: 0.05),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: Colors.white.withValues(alpha: 0.1)),
      ),
      child: TextField(
        controller: _titleController,
        style: SeedlingTypography.body.copyWith(color: Colors.white),
        decoration: InputDecoration(
          hintText: 'Enter Arena Legend...',
          hintStyle: TextStyle(color: Colors.white.withValues(alpha: 0.3)),
          prefixIcon: const Icon(
            Icons.edit_note_rounded,
            color: SeedlingColors.autumnGold,
          ),
          border: InputBorder.none,
          contentPadding: const EdgeInsets.all(20),
        ),
      ),
    );
  }

  Widget _buildModeSelection() {
    return Row(
      children: [
        Expanded(
          child: _buildGlassModeCard(
            title: 'Vocabulary',
            description: 'Blitz words',
            icon: '🌸',
            isSelected: _gameType == LiveGameType.vocabulary,
            onTap: () => setState(() => _gameType = LiveGameType.vocabulary),
          ),
        ),
        const SizedBox(width: 16),
        Expanded(
          child: _buildGlassModeCard(
            title: 'Sentences',
            description: 'Master syntax',
            icon: '🌳',
            isSelected: _gameType == LiveGameType.sentences,
            onTap: () => setState(() => _gameType = LiveGameType.sentences),
          ),
        ),
      ],
    );
  }

  Widget _buildGlassModeCard({
    required String title,
    required String description,
    required String icon,
    required bool isSelected,
    required VoidCallback onTap,
  }) {
    return GestureDetector(
      onTap: onTap,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 300),
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          color: isSelected
              ? SeedlingColors.seedlingGreen.withValues(alpha: 0.2)
              : Colors.white.withValues(alpha: 0.03),
          borderRadius: BorderRadius.circular(24),
          border: Border.all(
            color: isSelected
                ? SeedlingColors.seedlingGreen.withValues(alpha: 0.5)
                : Colors.white.withValues(alpha: 0.1),
            width: isSelected ? 2 : 1,
          ),
          boxShadow: isSelected
              ? [
                  BoxShadow(
                    color: SeedlingColors.seedlingGreen.withValues(alpha: 0.2),
                    blurRadius: 15,
                    spreadRadius: 1,
                  ),
                ]
              : [],
        ),
        child: Column(
          children: [
            Text(icon, style: const TextStyle(fontSize: 40)),
            const SizedBox(height: 12),
            Text(
              title,
              style: SeedlingTypography.body.copyWith(
                color: Colors.white,
                fontWeight: FontWeight.bold,
              ),
            ),
            Text(
              description,
              style: SeedlingTypography.caption.copyWith(color: Colors.white60),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildThemeSelector() {
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      physics: const BouncingScrollPhysics(),
      child: Row(
        children: _themes.map((theme) {
          final isSelected = _selectedTheme == theme;
          return Padding(
            padding: const EdgeInsets.only(right: 12),
            child: GestureDetector(
              onTap: () => setState(() => _selectedTheme = theme),
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 200),
                padding: const EdgeInsets.symmetric(
                  horizontal: 20,
                  vertical: 12,
                ),
                decoration: BoxDecoration(
                  color: isSelected
                      ? SeedlingColors.autumnGold
                      : Colors.white.withValues(alpha: 0.05),
                  borderRadius: BorderRadius.circular(30),
                  border: Border.all(
                    color: isSelected ? Colors.white24 : Colors.white12,
                  ),
                ),
                child: Text(
                  theme,
                  style: SeedlingTypography.body.copyWith(
                    color: isSelected ? Colors.black87 : Colors.white,
                    fontWeight: isSelected
                        ? FontWeight.bold
                        : FontWeight.normal,
                  ),
                ),
              ),
            ),
          );
        }).toList(),
      ),
    );
  }

  Widget _buildParameterControls() {
    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: Colors.white.withValues(alpha: 0.03),
        borderRadius: BorderRadius.circular(30),
        border: Border.all(color: Colors.white.withValues(alpha: 0.05)),
      ),
      child: Column(
        children: [
          _buildGlassSlider(
            label: 'Questions',
            value: _questionCount.toDouble(),
            min: 5,
            max: 30,
            icon: Icons.quiz_rounded,
            onChanged: (val) => setState(() => _questionCount = val.toInt()),
          ),
          const Padding(
            padding: EdgeInsets.symmetric(vertical: 16),
            child: Divider(color: Colors.white10),
          ),
          _buildGlassSlider(
            label: 'Time Limit (s)',
            value: _timeLimit.toDouble(),
            min: 5,
            max: 30,
            icon: Icons.timer_rounded,
            color: SeedlingColors.sunlight,
            onChanged: (val) => setState(() => _timeLimit = val.toInt()),
          ),
          const Padding(
            padding: EdgeInsets.symmetric(vertical: 16),
            child: Divider(color: Colors.white10),
          ),
          _buildGlassSlider(
            label: 'Max Warriors',
            value: _maxPlayers.toDouble(),
            min: 2,
            max: 10,
            icon: Icons.groups_rounded,
            color: SeedlingColors.water,
            onChanged: (val) => setState(() => _maxPlayers = val.toInt()),
          ),
        ],
      ),
    );
  }

  Widget _buildGlassSlider({
    required String label,
    required double value,
    required double min,
    required double max,
    required IconData icon,
    Color color = SeedlingColors.autumnGold,
    required ValueChanged<double> onChanged,
  }) {
    return Column(
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Row(
              children: [
                Icon(icon, color: color, size: 20),
                const SizedBox(width: 12),
                Text(
                  label,
                  style: SeedlingTypography.body.copyWith(
                    color: Colors.white70,
                  ),
                ),
              ],
            ),
            Text(
              '${value.toInt()}',
              style: SeedlingTypography.heading3.copyWith(color: color),
            ),
          ],
        ),
        const SizedBox(height: 8),
        SliderTheme(
          data: SliderTheme.of(context).copyWith(
            activeTrackColor: color,
            inactiveTrackColor: Colors.white10,
            thumbColor: Colors.white,
            overlayColor: color.withValues(alpha: 0.2),
            trackHeight: 2,
          ),
          child: Slider(value: value, min: min, max: max, onChanged: onChanged),
        ),
      ],
    );
  }

  Widget _buildHostToggle() {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white.withValues(alpha: 0.05),
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: Colors.white.withValues(alpha: 0.1)),
      ),
      child: SwitchListTile(
        title: Text(
          'Join the Battle?',
          style: SeedlingTypography.body.copyWith(
            color: Colors.white,
            fontWeight: FontWeight.bold,
          ),
        ),
        subtitle: Text(
          'Enter as a warrior or just observe.',
          style: SeedlingTypography.caption.copyWith(color: Colors.white60),
        ),
        value: _playAsParticipant,
        activeThumbColor: SeedlingColors.autumnGold,
        inactiveThumbColor: Colors.white24,
        onChanged: (val) => setState(() => _playAsParticipant = val),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
      ),
    );
  }

  Widget _buildCreateButton() {
    return ScaleTransition(
      scale: _pulseAnimation,
      child: GestureDetector(
        onTap: _createGame,
        child: Container(
          width: double.infinity,
          height: 70,
          decoration: BoxDecoration(
            gradient: const LinearGradient(
              colors: [SeedlingColors.autumnGold, Color(0xFFFFB300)],
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
            ),
            borderRadius: BorderRadius.circular(24),
            boxShadow: [
              BoxShadow(
                color: SeedlingColors.autumnGold.withValues(alpha: 0.3),
                blurRadius: 20,
                offset: const Offset(0, 10),
              ),
            ],
          ),
          alignment: Alignment.center,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Icon(Icons.bolt_rounded, color: Colors.black, size: 28),
              const SizedBox(width: 12),
              Text(
                'IGNITE ARENA',
                style: SeedlingTypography.heading3.copyWith(
                  color: Colors.black,
                  fontWeight: FontWeight.w900,
                  letterSpacing: 2,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
