import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/colors.dart';
import '../../../core/typography.dart';
import '../../../models/multiplayer.dart';
import '../../../providers/multiplayer_provider.dart';
import '../../../providers/app_providers.dart';
import '../../../core/page_route.dart';
import 'multiplayer_lobby_screen.dart';

class HostSetupScreen extends ConsumerStatefulWidget {
  const HostSetupScreen({super.key});

  @override
  ConsumerState<HostSetupScreen> createState() => _HostSetupScreenState();
}

class _HostSetupScreenState extends ConsumerState<HostSetupScreen> {
  String _selectedTheme = 'Daily Life';
  LiveGameType _gameType = LiveGameType.vocabulary;
  int _questionCount = 10;
  int _timeLimit = 15;
  int _maxPlayers = 5;
  bool _playAsParticipant = true;
  final TextEditingController _titleController = TextEditingController(text: 'My Forest Quiz');

  final List<String> _themes = [
    'Daily Life',
    'Universal Verbs',
    'Time & Space',
    'Grammar Functions',
    'Society & Culture'
  ];

  Future<void> _createGame() async {
    // Show loading
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => const Center(child: CircularProgressIndicator(color: SeedlingColors.seedlingGreen)),
    );

    try {
      final session = LiveGameSession(
        id: '', // Generated by DB
        hostId: '', // Set by provider
        hostName: '', 
        title: _titleController.text,
        gameType: _gameType,
        theme: _selectedTheme,
        subtheme: 'General',
        totalQuestions: _questionCount,
        timePerQuestion: _timeLimit,
        maxPlayers: _maxPlayers,
        languageCode: ref.read(nativeLanguageProvider),
        targetLanguageCode: ref.read(currentLanguageProvider),
      );

      await ref.read(activeSessionProvider.notifier).hostGame(session);

      if (mounted) {
        Navigator.pop(context); // Close loading
        Navigator.pushReplacement(
          context,
          SeedlingPageRoute(page: MultiplayerLobbyScreen(session: ref.read(activeSessionProvider)!)),
        );
      }
    } catch (e) {
      if (mounted) {
        Navigator.pop(context); // Close loading
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to create arena: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: SeedlingColors.background,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: SeedlingColors.textPrimary),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text('Host Quiz Arena', style: SeedlingTypography.heading3),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Title Input
            Text('Quiz Title', style: SeedlingTypography.heading3),
            const SizedBox(height: 10),
            TextField(
              controller: _titleController,
              decoration: InputDecoration(
                filled: true,
                fillColor: SeedlingColors.cardBackground,
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(16),
                  borderSide: BorderSide.none,
                ),
                contentPadding: const EdgeInsets.all(16),
              ),
            ),
            
            const SizedBox(height: 30),

            // Game Mode Selection
            Text('Game Mode', style: SeedlingTypography.heading3),
            const SizedBox(height: 15),
            Row(
              children: [
                Expanded(
                  child: _buildModeCard(
                    title: 'Vocabulary',
                    icon: '🌸',
                    isSelected: _gameType == LiveGameType.vocabulary,
                    onTap: () => setState(() => _gameType = LiveGameType.vocabulary),
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: _buildModeCard(
                    title: 'Sentences',
                    icon: '🌳',
                    isSelected: _gameType == LiveGameType.sentences,
                    onTap: () => setState(() => _gameType = LiveGameType.sentences),
                  ),
                ),
              ],
            ),
            
            const SizedBox(height: 30),

            // Theme Selection
            Text('Select Theme', style: SeedlingTypography.heading3),
            const SizedBox(height: 15),
            Wrap(
              spacing: 12,
              runSpacing: 12,
              children: _themes.map((t) => _buildOptionChip(
                label: t,
                isSelected: _selectedTheme == t,
                onTap: () => setState(() => _selectedTheme = t),
              )).toList(),
            ),

            const SizedBox(height: 30),

            // Question Count
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text('Questions', style: SeedlingTypography.heading3),
                Text('$_questionCount', style: SeedlingTypography.heading2.copyWith(color: SeedlingColors.seedlingGreen)),
              ],
            ),
            Slider(
              value: _questionCount.toDouble(),
              min: 5,
              max: 30,
              divisions: 5,
              activeColor: SeedlingColors.seedlingGreen,
              onChanged: (val) => setState(() => _questionCount = val.toInt()),
            ),

            const SizedBox(height: 30),
            
            Slider(
              value: _timeLimit.toDouble(),
              min: 5,
              max: 30,
              divisions: 5,
              activeColor: SeedlingColors.sunlight,
              onChanged: (val) => setState(() => _timeLimit = val.toInt()),
            ),

            const SizedBox(height: 30),
            
            // Max Players Count
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text('Max Players', style: SeedlingTypography.heading3),
                Text('$_maxPlayers', style: SeedlingTypography.heading2.copyWith(color: SeedlingColors.water)),
              ],
            ),
            Slider(
              value: _maxPlayers.toDouble(),
              min: 2,
              max: 10,
              divisions: 8,
              activeColor: SeedlingColors.water,
              onChanged: (val) => setState(() => _maxPlayers = val.toInt()),
            ),

            const SizedBox(height: 30),
            
            // Host Mode
            Text('Host Options', style: SeedlingTypography.heading3),
            const SizedBox(height: 15),
            Container(
              decoration: BoxDecoration(
                color: SeedlingColors.cardBackground,
                borderRadius: BorderRadius.circular(16),
                border: Border.all(color: SeedlingColors.morningDew.withOpacity(0.3)),
              ),
              child: SwitchListTile(
                title: Text('Play in your own game?', style: SeedlingTypography.body.copyWith(fontWeight: FontWeight.w600)),
                subtitle: Text('Turn off to just manage the lobby and observe.', style: SeedlingTypography.caption),
                value: _playAsParticipant,
                activeColor: SeedlingColors.seedlingGreen,
                onChanged: (val) => setState(() => _playAsParticipant = val),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
              ),
            ),
          ],
        ),
      ),
      bottomNavigationBar: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: GestureDetector(
            onTap: _createGame,
            child: Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(vertical: 20),
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                  colors: [SeedlingColors.deepRoot, SeedlingColors.seedlingGreen],
                ),
                borderRadius: BorderRadius.circular(20),
                boxShadow: [
                  BoxShadow(
                    color: SeedlingColors.seedlingGreen.withOpacity(0.4),
                    blurRadius: 15,
                    offset: const Offset(0, 5),
                  ),
                ],
              ),
              alignment: Alignment.center,
              child: Text(
                'Create Live Quiz',
                style: SeedlingTypography.body.copyWith(color: Colors.white, fontWeight: FontWeight.bold),
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildOptionChip({required String label, required bool isSelected, required VoidCallback onTap}) {
    return GestureDetector(
      onTap: onTap,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
        decoration: BoxDecoration(
          color: isSelected ? SeedlingColors.seedlingGreen : SeedlingColors.cardBackground,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            color: isSelected ? Colors.transparent : SeedlingColors.morningDew.withOpacity(0.3),
          ),
        ),
        child: Text(
          label,
          style: SeedlingTypography.body.copyWith(
            color: isSelected ? Colors.white : SeedlingColors.textPrimary,
            fontWeight: isSelected ? FontWeight.w600 : FontWeight.normal,
          ),
        ),
      ),
    );
  }

  Widget _buildModeCard({required String title, required String icon, required bool isSelected, required VoidCallback onTap}) {
    return GestureDetector(
      onTap: onTap,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        padding: const EdgeInsets.symmetric(vertical: 20),
        decoration: BoxDecoration(
          color: isSelected ? SeedlingColors.water.withOpacity(0.1) : SeedlingColors.cardBackground,
          borderRadius: BorderRadius.circular(20),
          border: Border.all(
            color: isSelected ? SeedlingColors.water : SeedlingColors.morningDew.withOpacity(0.3),
            width: isSelected ? 2 : 1,
          ),
          boxShadow: isSelected ? [BoxShadow(color: SeedlingColors.water.withOpacity(0.2), blurRadius: 10)] : [],
        ),
        child: Column(
          children: [
            Text(icon, style: const TextStyle(fontSize: 32)),
            const SizedBox(height: 8),
            Text(
              title,
              style: SeedlingTypography.body.copyWith(
                fontWeight: isSelected ? FontWeight.w700 : FontWeight.normal,
                color: isSelected ? SeedlingColors.deepRoot : SeedlingColors.textSecondary,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

